source 'https://github.com/CocoaPods/Specs.git'

# Required for Swift apps
platform :ios, '9.0'
use_frameworks!

# The target name is most likely the name of your project.
target 'ReactNativeExistingiOS' do

  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  def fix_unused_yoga_headers
    filepath = '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'

    contents = []

    file = File.open(filepath, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close

    if contents[43].include?('end')
        contents.insert(43, "  spec.public_header_files = 'yoga/Yoga.h', 'yoga/YGEnums.h', 'yoga/YGMacros.h'")
        contents.insert(43, "  # Only expose the needed headers")
        contents.insert(43, '')

        file = File.open(filepath, 'w') do |f|
            f.puts(contents)
        end
    end
  end

  def fix_incorrect_fishhook_header
    filepath = '../node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m'

    contents = []

    file = File.open(filepath, 'r')
    file.each_line do | line |
        contents << line
    end
    file.close

    if contents[11].include?('<fishhook/fishhook.h>')
        contents[11] = '#import "fishhook.h"'

        file = File.open(filepath, 'w') do |f|
            f.puts(contents)
        end
    end
  end

  def react_native_fix
    fix_unused_yoga_headers
    fix_incorrect_fishhook_header
  end

  pre_install do |installer|
    react_native_fix
  end
end
